                      // FOR REGISTRATION TESTING CODE HERE
# POST http://localhost:8000/api/v1/user/register
# Content-Type: application/json

# {
#   "firstName": "Jitesh",
#   "lastName": "Kumar",
#   "email": "yjitesh3203@gmail.com",
#   "password": "123456"
# }

                          // FOR REVERIFY TESTING CODE HERE
# POST http://localhost:8000/api/v1/user/reverify
# Content-Type: application/json

# {
#   "email": "yjitesh3203@gmail.com"
# }

                            // FOR VERIFY TESTING CODE HERE
# POST http://localhost:8000/api/v1/user/verify
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NTRhMDZmNTZiMDA1ZWM3NzAwYTg0NyIsImlhdCI6MTc2NzE1NjQ3MSwiZXhwIjoxNzY3MTU3MDcxfQ.ea_gOhi_1KeBIRxKoqH5JRqfZcYoF8Dv5L9SAKm8d8I


                           // FOR LOGIN TESTING CODE HERE
# POST http://localhost:8000/api/v1/user/login
# Content-Type: application/json

# {
#   "email": "yjitesh3203@gmail.com",
#   "password": "123456"
# }


                           // FOR LOGGOUT TESTING CODE HERE
# POST http://localhost:8000/api/v1/user/logout
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NDViMDFlY2MyYzA2NzUyNWRiMjIyZSIsImlhdCI6MTc2NjE4MTMzNywiZXhwIjoxNzY3MDQ1MzM3fQ.z5nUFf88ycu25KBzSJAZwLc3yXkEVXslz9XYOb89_jA



### Forgot Password
# POST http://localhost:8000/api/v1/user/forgot-password
# Content-Type: application/json

# {
#   "email": "jitesh3203@gmail.com"
# }


### Verify OTP
# POST http://localhost:8000/api/v1/user/verify-otp
# Content-Type: application/json

# {
#   "email": "jitesh3203@gmail.com",
#   "otp": "297505"
# }



### Change Password
# POST http://localhost:8000/api/v1/user/change-password/jitesh3203@gmail.com
# Content-Type: application/json

# {
#   "newPassword": "123456",
#   "confirmPassword": "123456"
# }



### Get all users
# GET http://localhost:8000/api/v1/user/all-user
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NDViMDFlY2MyYzA2NzUyNWRiMjIyZSIsImlhdCI6MTc2NjI2MTg2NywiZXhwIjoxNzY3MTI1ODY3fQ.0OZE52yyaigLS2q4Gda80ukXMmAanfJB-ancQ5eID1Y

















             // END OF FILE     ONLINE  BACKEND  SERVER TEST HTTP

             ### ROOT CHECK
GET https://e-kart-2vqj.onrender.com/

###

### GET ALL PRODUCTS
# GET https://e-kart-2vqj.onrender.com/api/v1/product

###

### REGISTER USER
### REGISTER USER
POST https://e-kart-2vqj.onrender.com/api/v1/user/register
Content-Type: application/json

{
   "firstName": "Test User",
  "lastName": "Kumar",
  "email": "testuser@gmail.com",
  "password": "123456"
}


###

### LOGIN USER
# POST https://e-kart-2vqj.onrender.com/api/v1/user/login
# Content-Type: application/json

# {
#   "email": "testuser1@gmail.com",
#   "password": "123456"
# }

###

### GET CART (AUTH REQUIRED)
# GET https://e-kart-2vqj.onrender.com/api/v1/cart
